"""add chunking and manifest tables

Revision ID: 4f8c1a2b7e33
Revises: 7b1f2d4e6a90
Create Date: 2026-07-18 11:00:00.000000

CIS Phase 2 Prompt 4 (Chunking, Knowledge Preparation & Processing
Orchestration — Phase 2's final milestone). Hand-written, not
autogenerated — see 41ff4259fcf2's docstring for why, and
docs/architecture/infrastructure/migration-guide.md for how this was
instead validated (a live SQLite ``Operations``/``MigrationContext``,
diffed column-for-column against ``Base.metadata``).

``chunks.parent_chunk_id`` self-references ``chunks.id`` — a plain
nullable self-FK, not a circular-pair situation like
9c3e7a1b5d84's ``documents``/``document_versions`` (that pair needed
``use_alter``/batch mode because each table referenced the *other*
before either existed; here the table references itself, which
``CREATE TABLE`` handles natively in one statement).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8c1a2b7e33"
down_revision: str | Sequence[str] | None = "7b1f2d4e6a90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=False),
        sa.Column("processing_job_id", sa.Uuid(), nullable=True),
        sa.Column("parent_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("strategy", sa.String(length=30), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("overlap_with_previous", sa.Integer(), nullable=False),
        sa.Column("chunk_metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["document_extractions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["processing_job_id"], ["processing_jobs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["parent_chunk_id"], ["chunks.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chunks_document_version_id"), "chunks", ["document_version_id"]
    )
    op.create_index(op.f("ix_chunks_extraction_id"), "chunks", ["extraction_id"])
    op.create_index(op.f("ix_chunks_parent_chunk_id"), "chunks", ["parent_chunk_id"])
    op.create_index(op.f("ix_chunks_strategy"), "chunks", ["strategy"])

    op.create_table(
        "document_manifests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("extraction_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("chunking_strategy", sa.String(length=30), nullable=True),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("total_character_count", sa.Integer(), nullable=False),
        sa.Column("statistics", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"], ["document_extractions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_version_id"),
    )
    op.create_index(
        op.f("ix_document_manifests_document_version_id"),
        "document_manifests",
        ["document_version_id"],
    )
    op.create_index(
        op.f("ix_document_manifests_status"), "document_manifests", ["status"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("document_manifests")
    op.drop_table("chunks")
