"""add conversations and messages tables

Revision ID: 5e40353ba43a
Revises: 9a2e5c8f1b47
Create Date: 2026-07-18 09:00:00.000000

CIS Phase 4 Prompt 2 (Conversational AI, Memory & Intelligent Sessions).
Hand-written, not autogenerated — see 41ff4259fcf2's docstring for why,
and docs/architecture/infrastructure/migration-guide.md for how this was
instead validated (a live SQLite ``Operations``/``MigrationContext``,
diffed column-for-column against ``Base.metadata``).

``messages.conversation_id`` references ``conversations.id`` — created
after ``conversations`` in this same migration, so no
``use_alter``/batch-mode workaround is needed (the same "child exists
after parent" ordering the entities/relationships migration used).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e40353ba43a"
down_revision: str | Sequence[str] | None = "9a2e5c8f1b47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summarized_through_sequence", sa.Integer(), nullable=False),
        sa.Column("conversation_metadata", sa.JSON(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_is_deleted"), "conversations", ["is_deleted"]
    )
    op.create_index(
        op.f("ix_conversations_organization_id"), "conversations", ["organization_id"]
    )
    op.create_index(
        op.f("ix_conversations_session_id"), "conversations", ["session_id"]
    )
    op.create_index(op.f("ix_conversations_status"), "conversations", ["status"])
    op.create_index(op.f("ix_conversations_user_id"), "conversations", ["user_id"])
    op.create_index(
        op.f("ix_conversations_workspace_id"), "conversations", ["workspace_id"]
    )

    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("citations", sa.JSON(), nullable=False),
        sa.Column("context_references", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"]
    )
    op.create_index(op.f("ix_messages_role"), "messages", ["role"])
    op.create_index(op.f("ix_messages_sequence_index"), "messages", ["sequence_index"])


def downgrade() -> None:
    """Downgrade schema — reverses upgrade() in strict FK-dependency order."""
    op.drop_table("messages")
    op.drop_table("conversations")
