"""add connector tables

Revision ID: 5e80424c81fd
Revises: 5e40353ba43a
Create Date: 2026-07-18 10:00:00.000000

CIS Phase 5 Prompt 1 (Enterprise Connectors & Knowledge Synchronization).
Hand-written, not autogenerated — see 41ff4259fcf2's docstring for why,
and docs/architecture/infrastructure/migration-guide.md for how this was
instead validated (a live SQLite ``Operations``/``MigrationContext``,
diffed column-for-column against ``Base.metadata``).

Three tables, created in dependency order: ``connectors`` (no
dependencies beyond workspaces/organizations/users, already present),
then ``connector_sync_runs`` and ``connector_sync_mappings`` (both
reference ``connectors.id``).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e80424c81fd"
down_revision: str | Sequence[str] | None = "5e40353ba43a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "connectors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("connector_type", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("auth_type", sa.String(length=30), nullable=False),
        sa.Column("credentials", sa.JSON(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("health_status", sa.String(length=20), nullable=False),
        sa.Column("health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_message", sa.String(length=2000), nullable=True),
        sa.Column("sync_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connectors_connector_type"), "connectors", ["connector_type"]
    )
    op.create_index(op.f("ix_connectors_is_deleted"), "connectors", ["is_deleted"])
    op.create_index(
        op.f("ix_connectors_organization_id"), "connectors", ["organization_id"]
    )
    op.create_index(op.f("ix_connectors_status"), "connectors", ["status"])
    op.create_index(op.f("ix_connectors_workspace_id"), "connectors", ["workspace_id"])

    op.create_table(
        "connector_sync_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("sync_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_discovered", sa.Integer(), nullable=False),
        sa.Column("items_processed", sa.Integer(), nullable=False),
        sa.Column("items_skipped", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.String(length=1000), nullable=True),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.Column("triggered_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["connector_id"], ["connectors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["triggered_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_sync_runs_connector_id"),
        "connector_sync_runs",
        ["connector_id"],
    )
    op.create_index(
        op.f("ix_connector_sync_runs_started_at"), "connector_sync_runs", ["started_at"]
    )
    op.create_index(
        op.f("ix_connector_sync_runs_status"), "connector_sync_runs", ["status"]
    )
    op.create_index(
        op.f("ix_connector_sync_runs_sync_type"), "connector_sync_runs", ["sync_type"]
    )
    op.create_index(
        op.f("ix_connector_sync_runs_workspace_id"),
        "connector_sync_runs",
        ["workspace_id"],
    )

    op.create_table(
        "connector_sync_mappings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("connector_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=500), nullable=False),
        sa.Column("external_url", sa.String(length=2000), nullable=True),
        sa.Column("external_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_checksum", sa.String(length=64), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["connector_id"], ["connectors.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "connector_id", "external_id", name="uq_connector_sync_mapping_external_id"
        ),
    )
    op.create_index(
        op.f("ix_connector_sync_mappings_connector_id"),
        "connector_sync_mappings",
        ["connector_id"],
    )
    op.create_index(
        op.f("ix_connector_sync_mappings_document_id"),
        "connector_sync_mappings",
        ["document_id"],
    )
    op.create_index(
        op.f("ix_connector_sync_mappings_external_id"),
        "connector_sync_mappings",
        ["external_id"],
    )
    op.create_index(
        op.f("ix_connector_sync_mappings_workspace_id"),
        "connector_sync_mappings",
        ["workspace_id"],
    )


def downgrade() -> None:
    """Downgrade schema — reverses upgrade() in strict FK-dependency order."""
    op.drop_table("connector_sync_mappings")
    op.drop_table("connector_sync_runs")
    op.drop_table("connectors")
