"""add document_extractions table

Revision ID: 7b1f2d4e6a90
Revises: 9c3e7a1b5d84
Create Date: 2026-07-18 10:00:00.000000

CIS Phase 2 Prompt 3 (Intelligent Document Processing Pipeline).
Hand-written, not autogenerated — see 41ff4259fcf2's docstring for why,
and docs/architecture/infrastructure/migration-guide.md for how this was
instead validated (a live SQLite ``Operations``/``MigrationContext``,
diffed column-for-column against ``Base.metadata``).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b1f2d4e6a90"
down_revision: str | Sequence[str] | None = "9c3e7a1b5d84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "document_extractions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("document_version_id", sa.Uuid(), nullable=False),
        sa.Column("processing_job_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("extracted_metadata", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_version_id"], ["document_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["processing_job_id"], ["processing_jobs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_version_id"),
    )
    op.create_index(
        op.f("ix_document_extractions_document_version_id"),
        "document_extractions",
        ["document_version_id"],
    )
    op.create_index(
        op.f("ix_document_extractions_status"), "document_extractions", ["status"]
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("document_extractions")
