"""add capsule tables

Revision ID: 7c2e4b8a1f36
Revises: 3f6a9d2c8e15
Create Date: 2026-07-19 09:00:00.000000

CIS Phase 5 Prompt 3 (Employee Knowledge Capsule / Digital
Organizational Twin). Hand-written, not autogenerated — see
41ff4259fcf2's docstring for why, and
docs/architecture/infrastructure/migration-guide.md for how this was
instead validated (a live SQLite ``Operations``/``MigrationContext``,
diffed column-for-column against ``Base.metadata``).

Three tables, created in dependency order: ``employee_knowledge_capsules``
(references ``users``/``entities``, both already present), then
``capsule_evidence_records`` (references ``employee_knowledge_capsules``
plus ``entities``/``relationships``/``documents``/``connectors``), then
``capsule_timeline_events`` (references
``employee_knowledge_capsules``/``capsule_evidence_records``).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c2e4b8a1f36"
down_revision: str | Sequence[str] | None = "3f6a9d2c8e15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "employee_knowledge_capsules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("person_entity_id", sa.Uuid(), nullable=True),
        sa.Column("organizational_role", sa.String(length=255), nullable=True),
        sa.Column("responsibilities", sa.JSON(), nullable=False),
        sa.Column("expertise_map", sa.JSON(), nullable=False),
        sa.Column("ownership_map", sa.JSON(), nullable=False),
        sa.Column("active_projects", sa.JSON(), nullable=False),
        sa.Column("collaboration_network", sa.JSON(), nullable=False),
        sa.Column("technical_leadership", sa.JSON(), nullable=False),
        sa.Column("capsule_metadata", sa.JSON(), nullable=False),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("stale_reason", sa.String(length=255), nullable=True),
        sa.Column("last_refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["person_entity_id"], ["entities.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "user_id"),
    )
    op.create_index(
        op.f("ix_employee_knowledge_capsules_is_deleted"),
        "employee_knowledge_capsules",
        ["is_deleted"],
    )
    op.create_index(
        op.f("ix_employee_knowledge_capsules_is_stale"),
        "employee_knowledge_capsules",
        ["is_stale"],
    )
    op.create_index(
        op.f("ix_employee_knowledge_capsules_organization_id"),
        "employee_knowledge_capsules",
        ["organization_id"],
    )
    op.create_index(
        op.f("ix_employee_knowledge_capsules_user_id"),
        "employee_knowledge_capsules",
        ["user_id"],
    )
    op.create_index(
        op.f("ix_employee_knowledge_capsules_workspace_id"),
        "employee_knowledge_capsules",
        ["workspace_id"],
    )

    op.create_table(
        "capsule_evidence_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capsule_id", sa.Uuid(), nullable=False),
        sa.Column("insight_type", sa.String(length=30), nullable=False),
        sa.Column("insight_key", sa.String(length=500), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("relationship_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("connector_id", sa.Uuid(), nullable=True),
        sa.Column("external_url", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["capsule_id"], ["employee_knowledge_capsules.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["connector_id"], ["connectors.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["entity_id"], ["entities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["relationship_id"], ["relationships.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capsule_evidence_records_capsule_id"),
        "capsule_evidence_records",
        ["capsule_id"],
    )
    op.create_index(
        op.f("ix_capsule_evidence_records_insight_type"),
        "capsule_evidence_records",
        ["insight_type"],
    )

    op.create_table(
        "capsule_timeline_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capsule_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("evidence_record_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["capsule_id"], ["employee_knowledge_capsules.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["evidence_record_id"],
            ["capsule_evidence_records.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capsule_timeline_events_capsule_id"),
        "capsule_timeline_events",
        ["capsule_id"],
    )
    op.create_index(
        op.f("ix_capsule_timeline_events_event_type"),
        "capsule_timeline_events",
        ["event_type"],
    )
    op.create_index(
        op.f("ix_capsule_timeline_events_occurred_at"),
        "capsule_timeline_events",
        ["occurred_at"],
    )


def downgrade() -> None:
    """Downgrade schema — reverses upgrade() in strict FK-dependency order."""
    op.drop_table("capsule_timeline_events")
    op.drop_table("capsule_evidence_records")
    op.drop_table("employee_knowledge_capsules")
