"""add entities and relationships tables

Revision ID: 9a2e5c8f1b47
Revises: 4f8c1a2b7e33
Create Date: 2026-07-25 09:00:00.000000

CIS Phase 3 Prompt 1 (Knowledge Graph & Entity Intelligence).
Hand-written, not autogenerated — see 41ff4259fcf2's docstring for why,
and docs/architecture/infrastructure/migration-guide.md for how this was
instead validated (a live SQLite ``Operations``/``MigrationContext``,
diffed column-for-column against ``Base.metadata``).

``relationships.source_entity_id``/``target_entity_id`` both reference
``entities.id`` — two plain foreign keys to the same table (not a
self-reference like Prompt 4's ``chunks.parent_chunk_id``, and not a
circular pair like Prompt 1's ``documents``/``document_versions`` —
``entities`` exists before ``relationships`` needs it, so no
``use_alter``/batch-mode workaround is needed here).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a2e5c8f1b47"
down_revision: str | Sequence[str] | None = "4f8c1a2b7e33"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("custom_type_name", sa.String(length=100), nullable=True),
        sa.Column("canonical_name", sa.String(length=500), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_entities_canonical_name"), "entities", ["canonical_name"]
    )
    op.create_index(op.f("ix_entities_entity_type"), "entities", ["entity_type"])
    op.create_index(op.f("ix_entities_is_deleted"), "entities", ["is_deleted"])
    op.create_index(
        op.f("ix_entities_organization_id"), "entities", ["organization_id"]
    )
    op.create_index(op.f("ix_entities_workspace_id"), "entities", ["workspace_id"])

    op.create_table(
        "relationships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("source_entity_id", sa.Uuid(), nullable=False),
        sa.Column("target_entity_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=30), nullable=False),
        sa.Column("custom_type_name", sa.String(length=100), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.String(length=2000), nullable=True),
        sa.Column("source_chunk_id", sa.Uuid(), nullable=True),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_chunk_id"], ["chunks.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"], ["entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"], ["entities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_relationships_is_deleted"), "relationships", ["is_deleted"]
    )
    op.create_index(
        op.f("ix_relationships_organization_id"), "relationships", ["organization_id"]
    )
    op.create_index(
        op.f("ix_relationships_relationship_type"),
        "relationships",
        ["relationship_type"],
    )
    op.create_index(
        op.f("ix_relationships_source_entity_id"),
        "relationships",
        ["source_entity_id"],
    )
    op.create_index(
        op.f("ix_relationships_target_entity_id"),
        "relationships",
        ["target_entity_id"],
    )
    op.create_index(
        op.f("ix_relationships_workspace_id"), "relationships", ["workspace_id"]
    )


def downgrade() -> None:
    """Downgrade schema — reverses upgrade() in strict FK-dependency order."""
    op.drop_table("relationships")
    op.drop_table("entities")
